### ISSUE TITLE
change to keep settings saved and make option to not save

### ISSUE THREAD

**Issue by wooloogooloo** [narcode/MIDI_recorder#1]

**Comment by wooloogooloo** [comment]
- Change terminal so that settings are saved
 - make option to not save recording
-Include the capture of the pedal in recording
- It's recording twice as fast as Im playing- or atleast it sounds twice as fast when I play it back in garageband (could be more than twice as fast)
- make the start up instructions clearer as discussed this morning
- super weird but my <impro2> file just saved the rhythms on one single note. Was it too long?

**Comment by narcode** [comment]
good idea. Will work on it

**Comment by narcode** [comment]
It's recording twice as fast as Im playing- or atleast it sounds twice as fast when I play it back in garageband (could be more than twice as fast) - done in v0.
super weird but my file just saved the rhythms on one single note. Was it too long? -> need to reproduce it.
