### ISSUE TITLE
Find a way so that users can save startup settings! 

### ISSUE THREAD

**Issue by narcode** [narcode/MIDI_recorder#3]
(i.e. device_id, midi_interface, etc) so they skip the interactive startup

**Comment by borrob** [comment]
That sounds like a job for``configparser``! https://docs.python.org/3/library/configparser.html 🏋️

**Comment by narcode** [comment]
shiiiiiiiiittttt that looks exactly like what we want!!! 🗡 🌞  

so can i count u in???

**Comment by borrob** [comment]
Sure... somehow github doesn't allow me to assign myself.

**Comment by narcode** [comment]
true. I also cannot assign you. I guess u need to do a PR first?
