### ISSUE TITLE
Give the option to not save recording at the end

### ISSUE THREAD

**Issue by narcode** [narcode/MIDI_recorder#4]

**Comment by borrob** [comment]
When no file name is provided, the file isn't saved. Check my commit f690191ede8c9fec7f0692c470973a95cd7d919d

**Comment by narcode** [comment]
where did u committed to? BTW i created branch 'develop v0.2' - feel also free tu suggest enhancements for this release

**Comment by borrob** [comment]
It's still in my dev-branch. I'll send a pull request later.
